//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExpressLocalizationResource_zh {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpressLocalizationResource_zh() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Web.LocalizationResources.ExpressLocalizationResource.zh", typeof(ExpressLocalizationResource_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string A_non_empty_request_body_is_required_ {
            get {
                return ResourceManager.GetString("A non-empty request body is required.", resourceCulture);
            }
        }
        
        public static string A_user_with_this_login_already_exists_ {
            get {
                return ResourceManager.GetString("A user with this login already exists.", resourceCulture);
            }
        }
        
        public static string A_value_for_the___0___parameter_or_property_was_not_provided_ {
            get {
                return ResourceManager.GetString("A value for the \'{0}\' parameter or property was not provided.", resourceCulture);
            }
        }
        
        public static string A_value_is_required_ {
            get {
                return ResourceManager.GetString("A value is required.", resourceCulture);
            }
        }
        
        public static string An_unknown_failure_has_occurred_ {
            get {
                return ResourceManager.GetString("An unknown failure has occurred.", resourceCulture);
            }
        }
        
        public static string Both_ErrorMessageResourceType_and_ErrorMessageResourceName_need_to_be_set_on_this_attribute_ {
            get {
                return ResourceManager.GetString("Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this" +
                        " attribute.", resourceCulture);
            }
        }
        
        public static string Cannot_retrieve_property___0___because_localization_failed___Type___1___is_not_public_or_does_not_contain_a_public_static_string_property_with_the_name___2___ {
            get {
                return ResourceManager.GetString("Cannot retrieve property \'{0}\' because localization failed.  Type \'{1}\' is not pu" +
                        "blic or does not contain a public static string property with the name \'{2}\'.", resourceCulture);
            }
        }
        
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        public static string Could_not_convert_the_value_of_type___0___to___1___as_expected_by_method__2___3__ {
            get {
                return ResourceManager.GetString("Could not convert the value of type \'{0}\' to \'{1}\' as expected by method {2}.{3}." +
                        "", resourceCulture);
            }
        }
        
        public static string Could_not_find_a_property_named__0__ {
            get {
                return ResourceManager.GetString("Could not find a property named {0}.", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string Either_ErrorMessageString_or_ErrorMessageResourceName_must_be_set__but_not_both_ {
            get {
                return ResourceManager.GetString("Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Email___0___is_already_taken_ {
            get {
                return ResourceManager.GetString("Email \'{0}\' is already taken.", resourceCulture);
            }
        }
        
        public static string Email___0___is_invalid_ {
            get {
                return ResourceManager.GetString("Email \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        public static string Incorrect_password_ {
            get {
                return ResourceManager.GetString("Incorrect password.", resourceCulture);
            }
        }
        
        public static string Invalid_token_ {
            get {
                return ResourceManager.GetString("Invalid token.", resourceCulture);
            }
        }
        
        public static string IsValid_object_value__has_not_been_implemented_by_this_class___The_preferred_entry_point_is_GetValidationResult___and_classes_should_override_IsValid_object_value__ValidationContext_context__ {
            get {
                return ResourceManager.GetString("IsValid(object value) has not been implemented by this class.  The preferred entr" +
                        "y point is GetValidationResult() and classes should override IsValid(object valu" +
                        "e, ValidationContext context).", resourceCulture);
            }
        }
        
        public static string Lockout_is_not_enabled_for_this_user_ {
            get {
                return ResourceManager.GetString("Lockout is not enabled for this user.", resourceCulture);
            }
        }
        
        public static string MaxLengthAttribute_must_have_a_Length_value_that_is_greater_than_zero__Use_MaxLength___without_parameters_to_indicate_that_the_string_or_array_can_have_the_maximum_allowable_length_ {
            get {
                return ResourceManager.GetString("MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLen" +
                        "gth() without parameters to indicate that the string or array can have the maxim" +
                        "um allowable length.", resourceCulture);
            }
        }
        
        public static string MetadataClassType_cannot_be_null_ {
            get {
                return ResourceManager.GetString("MetadataClassType cannot be null.", resourceCulture);
            }
        }
        
        public static string MinLengthAttribute_must_have_a_Length_value_that_is_zero_or_greater_ {
            get {
                return ResourceManager.GetString("MinLengthAttribute must have a Length value that is zero or greater.", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Optimistic_concurrency_failure__object_has_been_modified_ {
            get {
                return ResourceManager.GetString("Optimistic concurrency failure, object has been modified.", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Passwords_must_be_at_least__0__characters_ {
            get {
                return ResourceManager.GetString("Passwords must be at least {0} characters.", resourceCulture);
            }
        }
        
        public static string Passwords_must_have_at_least_one_digit___0___9___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one digit (\'0\'-\'9\').", resourceCulture);
            }
        }
        
        public static string Passwords_must_have_at_least_one_lowercase___a___z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one lowercase (\'a\'-\'z\').", resourceCulture);
            }
        }
        
        public static string Passwords_must_have_at_least_one_non_alphanumeric_character_ {
            get {
                return ResourceManager.GetString("Passwords must have at least one non alphanumeric character.", resourceCulture);
            }
        }
        
        public static string Passwords_must_have_at_least_one_uppercase___A___Z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one uppercase (\'A\'-\'Z\').", resourceCulture);
            }
        }
        
        public static string Passwords_must_use_at_least__0__different_characters_ {
            get {
                return ResourceManager.GetString("Passwords must use at least {0} different characters.", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Recovery_code_redemption_failed_ {
            get {
                return ResourceManager.GetString("Recovery code redemption failed.", resourceCulture);
            }
        }
        
        public static string Role_name___0___is_already_taken_ {
            get {
                return ResourceManager.GetString("Role name \'{0}\' is already taken.", resourceCulture);
            }
        }
        
        public static string Role_name___0___is_invalid_ {
            get {
                return ResourceManager.GetString("Role name \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        public static string The_argument___0___cannot_be_null__empty_or_contain_only_whitespace_ {
            get {
                return ResourceManager.GetString("The argument \'{0}\' cannot be null, empty or contain only whitespace.", resourceCulture);
            }
        }
        
        public static string The_associated_metadata_type_for_type___0___contains_the_following_unknown_properties_or_fields___1___Please_make_sure_that_the_names_of_these_members_match_the_names_of_the_properties_on_the_main_type_ {
            get {
                return ResourceManager.GetString("The associated metadata type for type \'{0}\' contains the following unknown proper" +
                        "ties or fields: {1}. Please make sure that the names of these members match the " +
                        "names of the properties on the main type.", resourceCulture);
            }
        }
        
        public static string The_custom_DataType_string_cannot_be_null_or_empty_ {
            get {
                return ResourceManager.GetString("The custom DataType string cannot be null or empty.", resourceCulture);
            }
        }
        
        public static string The_custom_validation_type___0___must_be_public_ {
            get {
                return ResourceManager.GetString("The custom validation type \'{0}\' must be public.", resourceCulture);
            }
        }
        
        public static string The_CustomValidationAttribute_method___0___does_not_exist_in_type___1___or_is_not_public_and_static_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute method \'{0}\' does not exist in type \'{1}\' or is not" +
                        " public and static.", resourceCulture);
            }
        }
        
        public static string The_CustomValidationAttribute_method___0___in_type___1___must_match_the_expected_signature__public_static_ValidationResult__0__object_value__ValidationContext_context____The_value_can_be_strongly_typed___The_ValidationContext_parameter_is_optional_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute method \'{0}\' in type \'{1}\' must match the expected " +
                        "signature: public static ValidationResult {0}(object value, ValidationContext co" +
                        "ntext).  The value can be strongly typed.  The ValidationContext parameter is op" +
                        "tional.", resourceCulture);
            }
        }
        
        public static string The_CustomValidationAttribute_method___0___in_type___1___must_return_System_ComponentModel_DataAnnotations_ValidationResult___Use_System_ComponentModel_DataAnnotations_ValidationResult_Success_to_represent_success_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute method \'{0}\' in type \'{1}\' must return System.Compo" +
                        "nentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnot" +
                        "ations.ValidationResult.Success to represent success.", resourceCulture);
            }
        }
        
        public static string The_CustomValidationAttribute_Method_was_not_specified_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute.Method was not specified.", resourceCulture);
            }
        }
        
        public static string The_CustomValidationAttribute_ValidatorType_was_not_specified_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute.ValidatorType was not specified.", resourceCulture);
            }
        }
        
        public static string The_field_must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field must be a number.", resourceCulture);
            }
        }
        
        public static string The_field_of_type__0__must_be_a_string__array_or_ICollection_type_ {
            get {
                return ResourceManager.GetString("The field of type {0} must be a string, array or ICollection type.", resourceCulture);
            }
        }
        
        public static string The_field__0__is_invalid_ {
            get {
                return ResourceManager.GetString("The field {0} is invalid.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field {0} must be a number.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_be_a_string_or_array_type_with_a_maximum_length_of___1___ {
            get {
                return ResourceManager.GetString("The field {0} must be a string or array type with a maximum length of \'{1}\'.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_be_a_string_or_array_type_with_a_minimum_length_of___1___ {
            get {
                return ResourceManager.GetString("The field {0} must be a string or array type with a minimum length of \'{1}\'.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_be_a_string_with_a_maximum_length_of__1__ {
            get {
                return ResourceManager.GetString("The field {0} must be a string with a maximum length of {1}.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_be_a_string_with_a_minimum_length_of__2__and_a_maximum_length_of__1__ {
            get {
                return ResourceManager.GetString("The field {0} must be a string with a minimum length of {2} and a maximum length " +
                        "of {1}.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_be_between__1__and__2__ {
            get {
                return ResourceManager.GetString("The field {0} must be between {1} and {2}.", resourceCulture);
            }
        }
        
        public static string The_field__0__must_match_the_regular_expression___1___ {
            get {
                return ResourceManager.GetString("The field {0} must match the regular expression \'{1}\'.", resourceCulture);
            }
        }
        
        public static string The_instance_provided_must_match_the_ObjectInstance_on_the_ValidationContext_supplied_ {
            get {
                return ResourceManager.GetString("The instance provided must match the ObjectInstance on the ValidationContext supp" +
                        "lied.", resourceCulture);
            }
        }
        
        public static string The_key_parameter_at_position__0__is_null__Every_key_control_parameter_must_be_a_string_ {
            get {
                return ResourceManager.GetString("The key parameter at position {0} is null. Every key control parameter must be a " +
                        "string.", resourceCulture);
            }
        }
        
        public static string The_key_parameter_at_position__0__with_value___1___is_not_a_string__Every_key_control_parameter_must_be_a_string_ {
            get {
                return ResourceManager.GetString("The key parameter at position {0} with value \'{1}\' is not a string. Every key con" +
                        "trol parameter must be a string.", resourceCulture);
            }
        }
        
        public static string The_key_parameter_at_position__0__with_value___1___occurs_more_than_once_ {
            get {
                return ResourceManager.GetString("The key parameter at position {0} with value \'{1}\' occurs more than once.", resourceCulture);
            }
        }
        
        public static string The_maximum_length_must_be_a_nonnegative_integer_ {
            get {
                return ResourceManager.GetString("The maximum length must be a nonnegative integer.", resourceCulture);
            }
        }
        
        public static string The_maximum_value___0___must_be_greater_than_or_equal_to_the_minimum_value___1___ {
            get {
                return ResourceManager.GetString("The maximum value \'{0}\' must be greater than or equal to the minimum value \'{1}\'." +
                        "", resourceCulture);
            }
        }
        
        public static string The_minimum_and_maximum_values_must_be_set_ {
            get {
                return ResourceManager.GetString("The minimum and maximum values must be set.", resourceCulture);
            }
        }
        
        public static string The_number_of_control_parameters_must_be_even_ {
            get {
                return ResourceManager.GetString("The number of control parameters must be even.", resourceCulture);
            }
        }
        
        public static string The_OperandType_must_be_set_when_strings_are_used_for_minimum_and_maximum_values_ {
            get {
                return ResourceManager.GetString("The OperandType must be set when strings are used for minimum and maximum values." +
                        "", resourceCulture);
            }
        }
        
        public static string The_pattern_must_be_set_to_a_valid_regular_expression_ {
            get {
                return ResourceManager.GetString("The pattern must be set to a valid regular expression.", resourceCulture);
            }
        }
        
        public static string The_property___0___on_resource_type___1___is_not_a_string_type_ {
            get {
                return ResourceManager.GetString("The property \'{0}\' on resource type \'{1}\' is not a string type.", resourceCulture);
            }
        }
        
        public static string The_property__0___1__could_not_be_found_ {
            get {
                return ResourceManager.GetString("The property {0}.{1} could not be found.", resourceCulture);
            }
        }
        
        public static string The_resource_type___0___does_not_have_an_accessible_static_property_named___1___ {
            get {
                return ResourceManager.GetString("The resource type \'{0}\' does not have an accessible static property named \'{1}\'.", resourceCulture);
            }
        }
        
        public static string The_supplied_value_is_invalid_for__0__ {
            get {
                return ResourceManager.GetString("The supplied value is invalid for {0}.", resourceCulture);
            }
        }
        
        public static string The_supplied_value_is_invalid_ {
            get {
                return ResourceManager.GetString("The supplied value is invalid.", resourceCulture);
            }
        }
        
        public static string The_type___0___does_not_contain_a_public_property_named___1___ {
            get {
                return ResourceManager.GetString("The type \'{0}\' does not contain a public property named \'{1}\'.", resourceCulture);
            }
        }
        
        public static string The_type___0___needs_to_represent_an_enumeration_type_ {
            get {
                return ResourceManager.GetString("The type \'{0}\' needs to represent an enumeration type.", resourceCulture);
            }
        }
        
        public static string The_type_provided_for_EnumDataTypeAttribute_cannot_be_null_ {
            get {
                return ResourceManager.GetString("The type provided for EnumDataTypeAttribute cannot be null.", resourceCulture);
            }
        }
        
        public static string The_type__0__must_implement__1__ {
            get {
                return ResourceManager.GetString("The type {0} must implement {1}.", resourceCulture);
            }
        }
        
        public static string The_value___0___is_invalid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        public static string The_value___0___is_not_valid_for__1__ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid for {1}.", resourceCulture);
            }
        }
        
        public static string The_value___0___is_not_valid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid.", resourceCulture);
            }
        }
        
        public static string The_value_for_property___0___must_be_of_type___1___ {
            get {
                return ResourceManager.GetString("The value for property \'{0}\' must be of type \'{1}\'.", resourceCulture);
            }
        }
        
        public static string The__0__field_is_not_a_valid_credit_card_number_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid credit card number.", resourceCulture);
            }
        }
        
        public static string The__0__field_is_not_a_valid_e_mail_address_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid e-mail address.", resourceCulture);
            }
        }
        
        public static string The__0__field_is_not_a_valid_fully_qualified_http__https__or_ftp_URL_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid fully-qualified http, https, or ftp URL.", resourceCulture);
            }
        }
        
        public static string The__0__field_is_not_a_valid_phone_number_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid phone number.", resourceCulture);
            }
        }
        
        public static string The__0__field_is_required_ {
            get {
                return ResourceManager.GetString("The {0} field is required.", resourceCulture);
            }
        }
        
        public static string The__0__field_only_accepts_files_with_the_following_extensions___1_ {
            get {
                return ResourceManager.GetString("The {0} field only accepts files with the following extensions: {1}", resourceCulture);
            }
        }
        
        public static string The__0__property_has_not_been_set___Use_the__1__method_to_get_the_value_ {
            get {
                return ResourceManager.GetString("The {0} property has not been set.  Use the {1} method to get the value.", resourceCulture);
            }
        }
        
        public static string User_already_has_a_password_set_ {
            get {
                return ResourceManager.GetString("User already has a password set.", resourceCulture);
            }
        }
        
        public static string User_already_in_role___0___ {
            get {
                return ResourceManager.GetString("User already in role \'{0}\'.", resourceCulture);
            }
        }
        
        public static string User_is_not_in_role___0___ {
            get {
                return ResourceManager.GetString("User is not in role \'{0}\'.", resourceCulture);
            }
        }
        
        public static string User_name___0___is_already_taken_ {
            get {
                return ResourceManager.GetString("User name \'{0}\' is already taken.", resourceCulture);
            }
        }
        
        public static string User_name___0___is_invalid__can_only_contain_letters_or_digits_ {
            get {
                return ResourceManager.GetString("User name \'{0}\' is invalid, can only contain letters or digits.", resourceCulture);
            }
        }
        
        public static string _0__is_not_valid_ {
            get {
                return ResourceManager.GetString("{0} is not valid.", resourceCulture);
            }
        }
        
        public static string ___0___and___1___do_not_match_ {
            get {
                return ResourceManager.GetString("\'{0}\' and \'{1}\' do not match.", resourceCulture);
            }
        }
        
        public static string _strong_The_Development_environment_shouldn_t_be_enabled_for_deployed_applications___strong__It_can_result_in_displaying_sensitive_information_from_exceptions_to_end_users__For_local_debugging__enable_the__strong_Development__strong__environment_by_setting_the__strong_ASPNETCORE_ENVIRONMENT__strong__environment_variable_to__strong_Development__strong__and_restarting_the_app {
            get {
                return ResourceManager.GetString(@"<strong>The Development environment shouldn't be enabled for deployed applications.</strong> It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong> and restarting the app", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string An_error_occurred_while_processing_your_request {
            get {
                return ResourceManager.GetString("An error occurred while processing your request", resourceCulture);
            }
        }
        
        public static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        public static string Development_Mode {
            get {
                return ResourceManager.GetString("Development Mode", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        public static string LazZiya_ExpressLocalization_Sample_Project {
            get {
                return ResourceManager.GetString("LazZiya.ExpressLocalization Sample Project", resourceCulture);
            }
        }
        
        public static string Learn_More {
            get {
                return ResourceManager.GetString("Learn More", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Please_enter_a_valid_number_ {
            get {
                return ResourceManager.GetString("Please enter a valid number.", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        public static string Request_ID {
            get {
                return ResourceManager.GetString("Request ID", resourceCulture);
            }
        }
        
        public static string Sample_Form {
            get {
                return ResourceManager.GetString("Sample Form", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Swapping_to_the__strong_Development__strong__environment_displays_detailed_information_about_the_error_that_occurred {
            get {
                return ResourceManager.GetString("Swapping to the <strong>Development</strong> environment displays detailed inform" +
                        "ation about the error that occurred", resourceCulture);
            }
        }
        
        public static string Use_a_local_account_to_log_in {
            get {
                return ResourceManager.GetString("Use a local account to log in", resourceCulture);
            }
        }
        
        public static string Use_another_service_to_log_in {
            get {
                return ResourceManager.GetString("Use another service to log in", resourceCulture);
            }
        }
        
        public static string Use_this_page_to_detail_your_site_s_privacy_policy {
            get {
                return ResourceManager.GetString("Use this page to detail your site\'s privacy policy", resourceCulture);
            }
        }
        
        public static string Use_this_space_to_summarize_your_privacy_and_cookie_use_policy {
            get {
                return ResourceManager.GetString("Use this space to summarize your privacy and cookie use policy", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        public static string AccountingTime {
            get {
                return ResourceManager.GetString("AccountingTime", resourceCulture);
            }
        }
        
        public static string ActionDuration {
            get {
                return ResourceManager.GetString("ActionDuration", resourceCulture);
            }
        }
        
        public static string ActualEndTime {
            get {
                return ResourceManager.GetString("ActualEndTime", resourceCulture);
            }
        }
        
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        public static string AmountMoney {
            get {
                return ResourceManager.GetString("AmountMoney", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        public static string CreatedDateTime {
            get {
                return ResourceManager.GetString("CreatedDateTime", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        public static string Department_Name {
            get {
                return ResourceManager.GetString("Department Name", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        public static string EnterpriseName {
            get {
                return ResourceManager.GetString("EnterpriseName", resourceCulture);
            }
        }
        
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        public static string FinancialType {
            get {
                return ResourceManager.GetString("FinancialType", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        public static string LockoutEnd {
            get {
                return ResourceManager.GetString("LockoutEnd", resourceCulture);
            }
        }
        
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string PhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmed", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        public static string RecordId {
            get {
                return ResourceManager.GetString("RecordId", resourceCulture);
            }
        }
        
        public static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        public static string Remember_Login {
            get {
                return ResourceManager.GetString("Remember Login", resourceCulture);
            }
        }
        
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ScheduleEndTime {
            get {
                return ResourceManager.GetString("ScheduleEndTime", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        public static string Sussess {
            get {
                return ResourceManager.GetString("Sussess", resourceCulture);
            }
        }
        
        public static string SysAction {
            get {
                return ResourceManager.GetString("SysAction", resourceCulture);
            }
        }
        
        public static string SysArea {
            get {
                return ResourceManager.GetString("SysArea", resourceCulture);
            }
        }
        
        public static string SysController {
            get {
                return ResourceManager.GetString("SysController", resourceCulture);
            }
        }
        
        public static string SysDefault {
            get {
                return ResourceManager.GetString("SysDefault", resourceCulture);
            }
        }
        
        public static string SysHelpClassId {
            get {
                return ResourceManager.GetString("SysHelpClassId", resourceCulture);
            }
        }
        
        public static string SystemId {
            get {
                return ResourceManager.GetString("SystemId", resourceCulture);
            }
        }
        
        public static string TaskExecutor {
            get {
                return ResourceManager.GetString("TaskExecutor", resourceCulture);
            }
        }
        
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        public static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }
        
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        public static string UpdatedDateTime {
            get {
                return ResourceManager.GetString("UpdatedDateTime", resourceCulture);
            }
        }
        
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        public static string UserCreatedBy {
            get {
                return ResourceManager.GetString("UserCreatedBy", resourceCulture);
            }
        }
        
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string UserUpdatedBy {
            get {
                return ResourceManager.GetString("UserUpdatedBy", resourceCulture);
            }
        }
        
        public static string ViewDuration {
            get {
                return ResourceManager.GetString("ViewDuration", resourceCulture);
            }
        }
        
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        public static string Demand {
            get {
                return ResourceManager.GetString("Demand", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        public static string Supply {
            get {
                return ResourceManager.GetString("Supply", resourceCulture);
            }
        }
        
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old Password", resourceCulture);
            }
        }
        
        public static string Update_password {
            get {
                return ResourceManager.GetString("Update password", resourceCulture);
            }
        }
        
        public static string Your_profile_has_been_updated {
            get {
                return ResourceManager.GetString("Your profile has been updated", resourceCulture);
            }
        }
        
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        public static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        public static string Forgot_password_confirmation {
            get {
                return ResourceManager.GetString("Forgot password confirmation", resourceCulture);
            }
        }
        
        public static string Custom_type {
            get {
                return ResourceManager.GetString("Custom type", resourceCulture);
            }
        }
        
        public static string Retrieve_password {
            get {
                return ResourceManager.GetString("Retrieve password", resourceCulture);
            }
        }
        
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        public static string User_Center {
            get {
                return ResourceManager.GetString("User Center", resourceCulture);
            }
        }
        
        public static string Nick_Name {
            get {
                return ResourceManager.GetString("Nick Name", resourceCulture);
            }
        }
        
        public static string System_Name {
            get {
                return ResourceManager.GetString("System Name", resourceCulture);
            }
        }
        
        public static string Hot_search {
            get {
                return ResourceManager.GetString("Hot search", resourceCulture);
            }
        }
        
        public static string Help_Center {
            get {
                return ResourceManager.GetString("Help Center", resourceCulture);
            }
        }
        
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        public static string Tutor {
            get {
                return ResourceManager.GetString("Tutor", resourceCulture);
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification Code", resourceCulture);
            }
        }
        
        public static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid username or password", resourceCulture);
            }
        }
        
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        public static string ContractContent {
            get {
                return ResourceManager.GetString("ContractContent", resourceCulture);
            }
        }
        
        public static string Contract_Type {
            get {
                return ResourceManager.GetString("Contract Type", resourceCulture);
            }
        }
        
        public static string ContractAmount {
            get {
                return ResourceManager.GetString("ContractAmount", resourceCulture);
            }
        }
        
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        public static string IDCardPhoto {
            get {
                return ResourceManager.GetString("IDCardPhoto", resourceCulture);
            }
        }
        
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        public static string OpeningBank {
            get {
                return ResourceManager.GetString("OpeningBank", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string ContractAttachments {
            get {
                return ResourceManager.GetString("ContractAttachments", resourceCulture);
            }
        }
        
        public static string BusinessLicense {
            get {
                return ResourceManager.GetString("BusinessLicense", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string Freelances {
            get {
                return ResourceManager.GetString("Freelances", resourceCulture);
            }
        }
        
        public static string Freelance {
            get {
                return ResourceManager.GetString("Freelance", resourceCulture);
            }
        }
        
        public static string ActualAmount {
            get {
                return ResourceManager.GetString("ActualAmount", resourceCulture);
            }
        }
        
        public static string AmountPayable {
            get {
                return ResourceManager.GetString("AmountPayable", resourceCulture);
            }
        }
        
        public static string TaxPayment {
            get {
                return ResourceManager.GetString("TaxPayment", resourceCulture);
            }
        }
        
        public static string CreditCode {
            get {
                return ResourceManager.GetString("CreditCode", resourceCulture);
            }
        }
        
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        public static string BusinessImage {
            get {
                return ResourceManager.GetString("BusinessImage", resourceCulture);
            }
        }
        
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        public static string SpecificDescription {
            get {
                return ResourceManager.GetString("SpecificDescription", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        public static string Personnel {
            get {
                return ResourceManager.GetString("Personnel", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string ServiceCharge {
            get {
                return ResourceManager.GetString("ServiceCharge", resourceCulture);
            }
        }
        
        public static string ServiceChargeId {
            get {
                return ResourceManager.GetString("ServiceChargeId", resourceCulture);
            }
        }
        
        public static string ServiceChargeSum {
            get {
                return ResourceManager.GetString("ServiceChargeSum", resourceCulture);
            }
        }
        
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        public static string FreelanceId {
            get {
                return ResourceManager.GetString("FreelanceId", resourceCulture);
            }
        }
        
        public static string Change_your_account_settings {
            get {
                return ResourceManager.GetString("Change your account settings", resourceCulture);
            }
        }
        
        public static string Manage_your_account {
            get {
                return ResourceManager.GetString("Manage your account", resourceCulture);
            }
        }
        
        public static string Enter_your_email_ {
            get {
                return ResourceManager.GetString("Enter your email.", resourceCulture);
            }
        }
        
        public static string resources {
            get {
                return ResourceManager.GetString("resources", resourceCulture);
            }
        }
        
        public static string Abnormal {
            get {
                return ResourceManager.GetString("Abnormal", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string YearMonth {
            get {
                return ResourceManager.GetString("YearMonth", resourceCulture);
            }
        }
        
        public static string Adopt {
            get {
                return ResourceManager.GetString("Adopt", resourceCulture);
            }
        }
        
        public static string SubmitAudit {
            get {
                return ResourceManager.GetString("SubmitAudit", resourceCulture);
            }
        }
        
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        public static string The_IDNumber_field_is_required_ {
            get {
                return ResourceManager.GetString("The IDNumber field is required.", resourceCulture);
            }
        }
        
        public static string Student_Certification {
            get {
                return ResourceManager.GetString("Student Certification", resourceCulture);
            }
        }
        
        public static string InstitutionName {
            get {
                return ResourceManager.GetString("InstitutionName", resourceCulture);
            }
        }
        
        public static string School_Certification {
            get {
                return ResourceManager.GetString("School Certification", resourceCulture);
            }
        }
        
        public static string UnifiedSocialCreditCode {
            get {
                return ResourceManager.GetString("UnifiedSocialCreditCode", resourceCulture);
            }
        }
        
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        public static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
        
        public static string AuditStatus {
            get {
                return ResourceManager.GetString("AuditStatus", resourceCulture);
            }
        }
    }
}
